OPENAI_API_KEY = "e83a3572341642228cd2fbd04b0b2da7"

[connections.snowflake_bscai]
user = "Jin"
password = "Bsci@1234"
#authenticator="EXTERNALBROWSER"
role = "EDH_COMM_DATA_LAKE_EMA_CHATBOT"
warehouse = "EDH_COMM_DATA_LAKE_EMA_CHATBOT_WH"
database= "CDL_DM"
schema= "DM"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "bscai"


[connections.snowflake_bsc]
type="snowflake"
user = "jin.zhou@bsci.com"
#password = ""
authenticator="EXTERNALBROWSER"
warehouse = "CDL_ANALYTICS_WH"
role = "EDH_COMM_DATA_LAKE_EMA_ACCESS"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "bsc.us-east-1"
